"""criação de tabela bacias hidrográficas e pivo

Revision ID: bde296bd6b91
Revises: 9b4c022148b2
Create Date: 2022-04-14 21:38:56.187863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde296bd6b91'
down_revision = '9b4c022148b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacias_hidrograficas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('bacias_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bacia_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bacia_id'], ['bacias_hidrograficas.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bacias_estados')
    op.drop_table('bacias_hidrograficas')
    # ### end Alembic commands ###
